forge 'forge.puppetlabs.com'

# Forge Modules to be included in our manifests.
mod 'puppetlabs/ntp', '6.2.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/apache', '2.1.0'
mod 'puppetlabs-apt', '4.2.0'
mod 'puppetlabs-concat', '4.0.1'
mod 'puppet-php', '5.0.0'
mod 'bzed-letsencrypt', '0.1.17'
mod 'puppet-archive', '2.1.0'
mod 'darin-zypprepo', '1.0.2'
mod 'puppetlabs-inifile', '2.0.0'
mod 'puppetlabs-vcsrepo', '2.0.0'
mod 'camptocamp-openssl', '1.10.0'
